default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: wp_development
test:
  <<: *default
  database: wp_test
production:
  <<: *default
  database: wp_production
